export const gyms = [
  {
    id: 1,
    title: "Power House Gym",
    image: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1",
    price: "EGP 800 - 1500 / month",
    location: "Cairo",
    category: "Bodybuilding",
    description: "State-of-the-art equipment with personal trainers specialized in strength training.",
  },
  {
    id: 2,
    title: "Fit Nation",
    image: "https://images.unsplash.com/photo-1554344728-77cf90d9ed26",
    price: "EGP 600 - 1200 / month",
    location: "Alexandria",
    category: "Fitness",
    description: "Modern fitness center with group classes, cardio zone, and yoga sessions.",
  },
  {
    id: 3,
    title: "Beast Mode Crossfit",
    image:"https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
    price: "EGP 700 - 1300 / month",
    location: "Giza",
    category: "Crossfit",
    description: "High intensity crossfit training and bootcamps with professional coaches.",
  },
  {
    id: 4,
    title: "Iron Paradise Gym",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
    price: "EGP 1000 - 1800 / month",
    location: "Cairo",
    category: "Bodybuilding",
    description: "Premium bodybuilding center with supplements shop and sauna facilities.",
  },
  {
    id: 5,
    title: "Zen Yoga Studio",
    image: "https://images.unsplash.com/photo-1554344728-77cf90d9ed26",
    price: "EGP 500 - 900 / month",
    location: "New Cairo",
    category: "Yoga",
    description: "Calm and peaceful yoga studio with meditation and wellness programs.",
  },
  {
    id: 6,
    title: "Fight Club MMA",
    image: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1",
    price: "EGP 700 - 1500 / month",
    location: "Alexandria",
    category: "Martial Arts",
    description: "Mixed Martial Arts training including boxing, jiu-jitsu, and kickboxing.",
  },
];
