export const resorts = [
  {
    id: 1,
    title: "Sea Breeze Resort",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: "EGP 2500 - 5000 / night",
    location: "Sharm El Sheikh",
    category: "Beachfront",
    description: "Luxury seaside resort with private beach, pools, and water sports activities.",
  },
  {
    id: 2,
    title: "Mountain View Retreat",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: "EGP 1800 - 4000 / night",
    location: "Sinai",
    category: "Nature",
    description: "Peaceful mountain resort offering hiking trails, campfires, and breathtaking views.",
  },
  {
    id: 3,
    title: "Oasis Desert Resort",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: "EGP 2000 - 4500 / night",
    location: "Siwa Oasis",
    category: "Desert",
    description: "Authentic desert experience with hot springs, palm groves, and cultural evenings.",
  },
  {
    id: 4,
    title: "Nile View Resort",
    image: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
    price: "EGP 2200 - 4800 / night",
    location: "Luxor",
    category: "Riverside",
    description: "Charming resort overlooking the Nile with cruises, fine dining, and spa facilities.",
  },
  {
    id: 5,
    title: "Paradise Island Resort",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: "EGP 3000 - 6000 / night",
    location: "Hurghada",
    category: "Island",
    description: "Exclusive island resort featuring snorkeling, diving, and luxury beachfront villas.",
  },
  {
    id: 6,
    title: "Green Valley Resort",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: "EGP 1500 - 3500 / night",
    location: "Fayoum",
    category: "Eco",
    description: "Eco-friendly resort surrounded by greenery, lakes, and traditional activities.",
  },
];
