export const restaurants = [
  {
    id: 1,
    title: "Italiano Restaurant",
    image: "https://media.timeout.com/images/105239239/750/562/image.jpg",
    price: "EGP 300 - 500 / person",
    location: "Cairo",
    category: "Italian",
    description: "Authentic Italian pasta, pizza and fine dining experience.",
  },
  {
    id: 2,
    title: "Seafood Palace",
    image: "https://media.timeout.com/images/105240189/750/562/image.jpg",
    price: "EGP 400 - 700 / person",
    location: "Alexandria",
    category: "Seafood",
    description: "Fresh seafood dishes with a sea view.",
  },
  {
    id: 3,
    title: "Oriental Grill",
    image: "https://media.timeout.com/images/105240191/750/562/image.jpg",
    price: "EGP 200 - 400 / person",
    location: "Giza",
    category: "Oriental",
    description: "Traditional Egyptian meals served with modern twist.",
  },
   {
    id: 4,
    title: "Italiano Restaurant",
    image: "https://media.timeout.com/images/105239239/750/562/image.jpg",
    price: "EGP 300 - 500 / person",
    location: "Cairo",
    category: "Italian",
    description: "Authentic Italian pasta, pizza and fine dining experience.",
  },
  {
    id: 5,
    title: "Seafood Palace",
    image: "https://media.timeout.com/images/105240189/750/562/image.jpg",
    price: "EGP 400 - 700 / person",
    location: "Alexandria",
    category: "Seafood",
    description: "Fresh seafood dishes with a sea view.",
  },
  {
    id: 6,
    title: "Oriental Grill",
    image: "https://media.timeout.com/images/105240191/750/562/image.jpg",
    price: "EGP 200 - 400 / person",
    location: "Giza",
    category: "Oriental",
    description: "Traditional Egyptian meals served with modern twist.",
  },
  
];
